### ISSUE TITLE
Not compatible with the Pixel 6?

### ISSUE THREAD

**Issue by khaytsus** [burton999dev/CalcNoteHelp#22]
Did you all break something? I can't update the app and can't even see it in the play store any more.,

**Comment by burton999dev** [comment]
What is your country?
Google is currently restricting paid app downloads from Russia.

https://support.google.com/googleplay/android-developer/answer/11950272?hl=en

**Comment by burton999dev** [comment]
I can access CalcNote and CalcNote Pro from Japan.

https://play.google.com/store/apps/details?id=com.burton999.notecal
https://play.google.com/store/apps/details?id=com.burton999.notecal.pro

**Comment by burton999dev** [comment]
Also recently Xiaomi users reported a similar problem.

https://github.com/burton999dev/CalcNoteHelp/issues/21

**Comment by khaytsus** [comment]
US, stock rom, not seeing any other apps do this offhand.  My bootloader is unlocked but otherwise the device has never been rooted, is 100% stock, etc.  And yes this does appear to be similar to what Netflix does to block downloads on devices that Safetynet is not passing, have you made some change to the app or the app settings in your dev console to block such devices?

**Comment by burton999dev** [comment]
Recently, Google play console implemented a new feature "Automatic Integrity Protection".
I tried to release CalcNote with this feature, but there was a bug, so I changed the setting to disabled.

https://issuetracker.google.com/u/1/issues/244211269

It is possible that there may be a bug in Google Play that is causing some of this functionality to function as enabled.
I will contact Google play console team.

**Comment by khaytsus** [comment]
@burton999dev Appreciate it, I've heard from a few other users of other apps they've also seen some apps go dark on them like this and then they showed back up and the developer said they did nothing to cause it and didn't understand themselves what was going on.  I wish Google would stop messing with stuff like this, especially making it default.

**Comment by liuli7700** [comment]
I have the same problem in xiaomi 12, and my country in play store is usa

**Comment by liuli7700** [comment]
> Recently, Google play console implemented a new feature "Automatic Integrity Protection". I tried to release CalcNote with this feature, but there was a bug, so I changed the setting to disabled.
> 
> https://issuetracker.google.com/u/1/issues/244211269
> 
> It is possible that there may be a bug in Google Play that is causing some of this functionality to function as enabled. I will contact Google play console team.

your link show that problem is fixed, but it's still not compatible @burton999dev

**Comment by burton999dev** [comment]
Hi @liuli7700 
Did you check this issue? https://github.com/burton999dev/CalcNoteHelp/issues/21

**Comment by liuli7700** [comment]
> Hi @liuli7700 Did you check this issue? #21

Thanks, the problem is solved, I locked bl and passed safetynet test

**Comment by khaytsus** [comment]
> > Hi @liuli7700 Did you check this issue? #21
> 
> Thanks, the problem is solved, I locked bl and passed safetynet test

That is NOT SOLVED.  This app should not be blocked by CTS failure, there's no reason for it.

**Comment by JLJTGR** [comment]
I would not accept a banking app refusing to work because of an unlocked bootloader.  I definitely will not accept a *calculator* app refusing to install because of the same thing.  Please consider not using this Play Store feature to block downloads/updates.  I bought the pro version because I thought it was a good app, but I do not condone practices such as this.

**Comment by liuli7700** [comment]
> I would not accept a banking app refusing to work because of an unlocked bootloader. I definitely will not accept a _calculator_ app refusing to install because of the same thing. Please consider not using this Play Store feature to block downloads/updates. I bought the pro version because I thought it was a good app, but I do not condone practices such as this.

you are right, that's unreasonable

**Comment by nfukuzaki** [comment]
I'm currently contacting Google support about this problem.
If this is caused by Automatic Integrity Protection, I will not activate this feature.
But, I have already disabled this feature, but it is possible that the device check is enabled for some reason.
Unfortunately, so far I have not received a reply from Google in over a week.
I cannot do anything about that.
Please email me your order number if you want a refund.

burton9999dev@gmail.comd

Best regards,

**Comment by burton999dev** [comment]
I'm currently contacting Google support about this problem.
If this is caused by Automatic Integrity Protection, I will not activate this feature.
But, I have already disabled this feature, but it is possible that the device check is enabled for some reason.
Unfortunately, so far I have not received a reply from Google in over a week.
I cannot do anything about that.
Please email me your order number if you want a refund.

[burton9999dev@gmail.comd](mailto:burton9999dev@gmail.comd)

Best regards,

**Comment by JLJTGR** [comment]
I wish you luck on getting Google to respond.  If their Play Store branch is anything like their YouTube creator branch, then the odds are very poor.

**Comment by burton999dev** [comment]
Unfortunately, the reply from Google Play Console team was not informative.
I created an issue for Google Issue Tracker.

https://issuetracker.google.com/u/1/issues/254199019

**Comment by liuli7700** [comment]
I think this problem is solved, the app can be installed in a cts failure phone.

**Comment by burton999dev** [comment]
Yes, I updated Device Exclusion settings.

https://issuetracker.google.com/u/1/issues/254199019

Thank you for your confirmation.
